FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY=:0

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    cmake \
    libasound2-dev \
    libx11-dev \
    libxrandr-dev \
    libxi-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    libxcursor-dev \
    libxinerama-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

# Download Raylib source
RUN git clone https://github.com/raysan5/raylib.git

# Build Raylib
WORKDIR /app/raylib/src
RUN make PLATFORM=PLATFORM_DESKTOP

# Back to app
WORKDIR /app

# Build your program
RUN g++ main.cpp -o app \
    -I./raylib/src \
    -L./raylib/src \
    -lraylib \
    -lGL \
    -lm \
    -lpthread \
    -ldl \
    -lrt \
    -lX11

CMD ["./app"]